### PR TITLE
Add TypeScript definitions

### PR DESCRIPTION
**Pull request by pjoe**
Adds definition file for TypeScript 🎨

### CODE REVIEW

**Comment by pjoe** [comment]
FYI: I also tried adding to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43487

**Comment by bruno-morel** [comment]
Tks, amazing job! I'll merge it

**Comment by bruno-morel** [comment]
Now that its merged, do you think we should add a documentation example for this?

**Comment by pjoe** [comment]
@bruno-morel yeah an example in docs would be good - will see if I can find some time to do a PR for that.

Also once released (is it already in 0.6.4?), then I guess the typings should be removed from DefinitelyTyped.

Btw. thanks for this great lib, makes adopting cucumber super smooth :)

**Comment by bruno-morel** [comment]
Yes it's already in 0.6.4. I bumped some libs too since there was an advisory.

Tks, unsurprisingly I made it for myself to not fight between jest and cucumber :)

Happy you found it and enjoy it!

Don't hesitate to PR the doc!

**Pull request merged**
