### PR TITLE
Upgrade jest cucumber to v3

### PR DESCRIPTION
**Pull request by stevensnoeijen**
Upgrade jest-cucumber to v3 and added test for language support

### CODE REVIEW

**Comment by bruno-morel** [comment]
Should we update the documentation/readme.md to reflec the examples ?

**Comment by stevensnoeijen** [comment]
> Should we update the documentation/readme.md to reflec the examples ?
Sure, how do you want it? :)

**Comment by bruno-morel** [comment]
Sorry for the delay . too busy.  It would be great to add a page in Additional Documentation ?

**Comment by stevensnoeijen** [comment]
ill soon create a new pr for a documentation page.

**Pull request merged**
