### PR TITLE
Roll back incorrect refactoring and add Scenario Outline tests

### PR DESCRIPTION
**Pull request by j8kin**
PR#27 has incorrect refactoring. This PR roll back it and add additional Scenario outline tests to avoid it in future.

### CODE REVIEW

**Comment by j8kin** [comment]
#32 should be fixed by this PR

**Review by bruno-morel — APPROVED** [review]
seem to do the job

**Comment by j8kin** [comment]
@bruno-morel could you merge pull request? it seems I dont have enough rights:
"Only those with write access to this repository can merge pull requests."
And by the way please also publish new version in NPM it seems it use you credentials to publish and I also not able to do this.

Best Regards,
Eugene...

**Comment by hmorey3** [comment]
@bruno-morel eager to see this PR in, any hesitations to merge?

**Comment by bruno-morel** [comment]
Seems like the owner (BYond) has removed my write rights...I'm working with them

**Comment by bruno-morel** [comment]
Ok, I have my rights back, but @j8kin , I would need you to fix the merge conflicts...

**Comment by j8kin** [comment]
@bruno-morel yep its my fault I forgot to fetch branch before commit but then I saw that:
"This branch has no conflicts with the base branch" and suppose that it's not a big deal and it would be merged automatically.
Sorry about that.

**Comment by hmorey3** [comment]
Sorry to bother you again, just checking in on the merge progress :)  @bruno-morel

**Comment by bruno-morel** [comment]
This branch cannot be rebased due to conflicts
you'll have to fix the conflicts

**Pull request closed without merging**
